# Generated by Django 3.2.12 on 2024-03-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapi.uploadedimage')),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadedresult',
            index=models.Index(fields=['uploaded_image'], name='modelapi_up_uploade_a6c68e_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadedresult',
            constraint=models.UniqueConstraint(fields=('uploaded_image',), name='unique_uploaded_image_result'),
        ),
    ]
