# Generated by Django 3.2.12 on 2024-03-31 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0003_processedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
