# Generated by Django 3.2.9 on 2024-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0005_auto_20240424_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='cup_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='cupdisc_ratio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='disc_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='s3_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
